spring:
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.RedisAutoConfiguration
      - org.springframework.boot.data.mongo.autoconfigure.MongoDataAutoConfiguration
      - org.springframework.boot.data.mongo.autoconfigure.MongoRepositoriesAutoConfiguration
      - org.springframework.ai.vectorstore.chroma.autoconfigure.ChromaVectorStoreAutoConfiguration
